auto: true
title: Tom Oakley
category_dir: ''
category_title_prefix: ''
category_meta_description_prefix: ''
description: "Designer & Developer"
permalink: /:categories/:title
# defaults
sass:
    syntax: scss        # scss|sass
    style:  compressed # nested|expanded|compact|compressed